# Generated by Django 2.0.5 on 2018-09-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_choices_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
